CONNECTION_CAPABILITY_TYPE_CREATE = 0
CONNECTION_CAPABILITY_TYPE_INVITE = 1

CONNECTION_HANDLE_TYPE_CONTACT = 0
CONNECTION_HANDLE_TYPE_ROOM = 1
CONNECTION_HANDLE_TYPE_LIST = 2

CONNECTION_PRESENCE_TYPE_OFFLINE = 0
CONNECTION_PRESENCE_TYPE_AVAILABLE = 1
CONNECTION_PRESENCE_TYPE_AWAY = 2
CONNECTION_PRESENCE_TYPE_EXTENDED_AWAY = 3
CONNECTION_PRESENCE_TYPE_HIDDEN = 4

CONNECTION_STATUS_CONNECTED = 0
CONNECTION_STATUS_CONNECTING = 1
CONNECTION_STATUS_DISCONNECTED = 2

CONNECTION_STATUS_REASON_NONE_SPECIFIED = 0
CONNECTION_STATUS_REASON_REQUESTED = 1
CONNECTION_STATUS_REASON_NETWORK_ERROR = 2
CONNECTION_STATUS_REASON_AUTHENTICATION_FAILED = 3
CONNECTION_STATUS_REASON_ENCRYPTION_ERROR = 4
